### ISSUE TITLE
开发环境清理缓存策略有问题

### ISSUE THREAD

**Issue by wxhccc** [jctaoo/electron-run#42]
开发环境的编译文件保存在node_modules/.electron-run/app目录下，但是目前重新运行会清空这个目录下的所有文件。
现在的问题是程序需要保存文件在软件安装目录下的自定义目录下，保存的文件在重新编译后就丢失了。
建议添加配置可以设置app文件夹下不会被清除的目录

**Comment by jctaoo** [comment]
🎉 感谢您的使用！

`node_modules/.electron-run/app` 被设计用来存储 `tsconfig` 和 编译后的文件 等。请问您的具体用例是什么，您使用类似于 `process.cwd()` 的方式来获取路径并保存文件嘛

**Comment by wxhccc** [comment]
> 🎉 感谢您的使用！
> 
> `node_modules/.electron-run/app` 被设计用来存储 `tsconfig` 和 编译后的文件 等。请问您的具体用例是什么，您使用类似于 `process.cwd()` 的方式来获取路径并保存文件嘛

具体场景是从本地选择图片设置为背景，图片保存在electron的getAppPath()函数返回的目录下自己创建的resource目录下，在编译环境下，这个目录是.electron-run/app。打包后，这个目录是程序安装目录

**Comment by jctaoo** [comment]
> > 🎉 感谢您的使用！
> > `node_modules/.electron-run/app` 被设计用来存储 `tsconfig` 和 编译后的文件 等。请问您的具体用例是什么，您使用类似于 `process.cwd()` 的方式来获取路径并保存文件嘛
> 
> 具体场景是从本地选择图片设置为背景，图片保存在electron的getAppPath()函数返回的目录下自己创建的resource目录下，在编译环境下，这个目录是.electron-run/app。打包后，这个目录是程序安装目录

OK，将提供一个 --clean-cache 参数，然后默认不清理

**Comment by jctaoo** [comment]
升级到 2.2.0 来使用新参数 `--clean-cache`

doc: https://elecrun.jctaoo.com/#option---clean-cache

**Comment by wxhccc** [comment]
> 升级到 2.2.0 来使用新参数 `--clean-cache`
> 
> doc: https://elecrun.jctaoo.com/#option---clean-cache

非常感谢及时响应，建议可以提供elecrun.config.(ts/js)配置文件，然后分base，dev，build 3个模块提供配置（之前建议内容），方便后期添加新功能，也可以有更详细的提示。

**Comment by jctaoo** [comment]
> > 升级到 2.2.0 来使用新参数 `--clean-cache`
> > doc: https://elecrun.jctaoo.com/#option---clean-cache
> 
> 非常感谢及时响应，建议可以提供elecrun.config.(ts/js)配置文件，然后分base，dev，build 3个模块提供配置（之前建议内容），方便后期添加新功能，也可以有更详细的提示。

Ok, 相关进度将在 #41 跟进，将关闭这个 issue
